# -*- encoding: utf-8 -*-

=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.3.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "cloudreactor_api_client/version"

Gem::Specification.new do |s|
  s.name        = "cloudreactor_api_client"
  s.version     = CloudReactorAPIClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Jeff Tsay"]
  s.email       = ["jeff@cloudreactor.io"]
  s.homepage    = "https://github.com/CloudReactor/cloudreactor-ruby-client-wrapperio"
  s.summary     = "CloudReactor API client and process wrapper communication"
  s.description = "API client to monitor and manage Tasks and Workflows in CloudReactor, and communication with a CloudReactor process wrapper"
  s.license     = "BSD-2-Clause"
  s.required_ruby_version = ">= 2.5"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files = Dir["{lib}/**/*.rb", "LICENSE.txt", "*.md"]
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
