=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudReactorAPIClient::AlertMethodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AlertMethodsApi' do
  before do
    # run before each test
    @api_instance = CloudReactorAPIClient::AlertMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AlertMethodsApi' do
    it 'should create an instance of AlertMethodsApi' do
      expect(@api_instance).to be_instance_of(CloudReactorAPIClient::AlertMethodsApi)
    end
  end

  # unit tests for alert_methods_clone_create
  # @param uuid 
  # @param alert_method 
  # @param [Hash] opts the optional parameters
  # @return [AlertMethod]
  describe 'alert_methods_clone_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for alert_methods_create
  # @param alert_method 
  # @param [Hash] opts the optional parameters
  # @return [AlertMethod]
  describe 'alert_methods_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for alert_methods_destroy
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'alert_methods_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for alert_methods_list
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :created_by_group__id 
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [String] :name 
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [String] :run_environment__uuid 
  # @option opts [String] :search A search term.
  # @return [PaginatedAlertMethodList]
  describe 'alert_methods_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for alert_methods_partial_update
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedAlertMethod] :patched_alert_method 
  # @return [AlertMethod]
  describe 'alert_methods_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for alert_methods_retrieve
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [AlertMethod]
  describe 'alert_methods_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for alert_methods_update
  # @param uuid 
  # @param alert_method 
  # @param [Hash] opts the optional parameters
  # @return [AlertMethod]
  describe 'alert_methods_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
