=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudReactorAPIClient::EmailNotificationProfilesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EmailNotificationProfilesApi' do
  before do
    # run before each test
    @api_instance = CloudReactorAPIClient::EmailNotificationProfilesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmailNotificationProfilesApi' do
    it 'should create an instance of EmailNotificationProfilesApi' do
      expect(@api_instance).to be_instance_of(CloudReactorAPIClient::EmailNotificationProfilesApi)
    end
  end

  # unit tests for email_notification_profiles_clone_create
  # @param uuid 
  # @param email_notification_profile 
  # @param [Hash] opts the optional parameters
  # @return [EmailNotificationProfile]
  describe 'email_notification_profiles_clone_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for email_notification_profiles_create
  # @param email_notification_profile 
  # @param [Hash] opts the optional parameters
  # @return [EmailNotificationProfile]
  describe 'email_notification_profiles_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for email_notification_profiles_destroy
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'email_notification_profiles_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for email_notification_profiles_list
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :created_by_group__id 
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [String] :name 
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [String] :run_environment__uuid 
  # @option opts [String] :search A search term.
  # @return [PaginatedEmailNotificationProfileList]
  describe 'email_notification_profiles_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for email_notification_profiles_partial_update
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedEmailNotificationProfile] :patched_email_notification_profile 
  # @return [EmailNotificationProfile]
  describe 'email_notification_profiles_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for email_notification_profiles_retrieve
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [EmailNotificationProfile]
  describe 'email_notification_profiles_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for email_notification_profiles_update
  # @param uuid 
  # @param email_notification_profile 
  # @param [Hash] opts the optional parameters
  # @return [EmailNotificationProfile]
  describe 'email_notification_profiles_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
