=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudReactorAPIClient::WorkflowTaskInstancesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WorkflowTaskInstancesApi' do
  before do
    # run before each test
    @api_instance = CloudReactorAPIClient::WorkflowTaskInstancesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkflowTaskInstancesApi' do
    it 'should create an instance of WorkflowTaskInstancesApi' do
      expect(@api_instance).to be_instance_of(CloudReactorAPIClient::WorkflowTaskInstancesApi)
    end
  end

  # unit tests for workflow_task_instances_create
  # @param workflow_task_instance 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowTaskInstance]
  describe 'workflow_task_instances_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_task_instances_destroy
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'workflow_task_instances_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_task_instances_list
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description 
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [String] :name 
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [String] :search A search term.
  # @option opts [String] :task__name 
  # @option opts [String] :task__uuid 
  # @option opts [Integer] :workflow__created_by_group__id 
  # @option opts [String] :workflow__run_environment__uuid 
  # @option opts [String] :workflow__uuid 
  # @return [PaginatedWorkflowTaskInstanceList]
  describe 'workflow_task_instances_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_task_instances_partial_update
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedWorkflowTaskInstance] :patched_workflow_task_instance 
  # @return [WorkflowTaskInstance]
  describe 'workflow_task_instances_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_task_instances_retrieve
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowTaskInstance]
  describe 'workflow_task_instances_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_task_instances_update
  # @param uuid 
  # @param workflow_task_instance 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowTaskInstance]
  describe 'workflow_task_instances_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
