=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudReactorAPIClient::WorkflowExecutionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WorkflowExecutionsApi' do
  before do
    # run before each test
    @api_instance = CloudReactorAPIClient::WorkflowExecutionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkflowExecutionsApi' do
    it 'should create an instance of WorkflowExecutionsApi' do
      expect(@api_instance).to be_instance_of(CloudReactorAPIClient::WorkflowExecutionsApi)
    end
  end

  # unit tests for workflow_executions_create
  # @param workflow_execution 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowExecution]
  describe 'workflow_executions_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_executions_destroy
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'workflow_executions_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_executions_list
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [String] :search A search term.
  # @option opts [String] :workflow__created_by_group__id 
  # @option opts [String] :workflow__uuid 
  # @return [PaginatedWorkflowExecutionSummaryList]
  describe 'workflow_executions_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_executions_partial_update
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedWorkflowExecution] :patched_workflow_execution 
  # @return [WorkflowExecution]
  describe 'workflow_executions_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_executions_retrieve
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowExecution]
  describe 'workflow_executions_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_executions_retry_create
  # @param uuid 
  # @param workflow_execution 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowExecution]
  describe 'workflow_executions_retry_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_executions_update
  # @param uuid 
  # @param workflow_execution 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowExecution]
  describe 'workflow_executions_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflow_executions_workflow_task_instance_executions_create
  # @param uuid 
  # @param workflow_execution 
  # @param [Hash] opts the optional parameters
  # @return [WorkflowExecution]
  describe 'workflow_executions_workflow_task_instance_executions_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
