=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudReactorAPIClient::WorkflowsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WorkflowsApi' do
  before do
    # run before each test
    @api_instance = CloudReactorAPIClient::WorkflowsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkflowsApi' do
    it 'should create an instance of WorkflowsApi' do
      expect(@api_instance).to be_instance_of(CloudReactorAPIClient::WorkflowsApi)
    end
  end

  # unit tests for workflows_clone_create
  # @param uuid 
  # @param workflow 
  # @param [Hash] opts the optional parameters
  # @return [Workflow]
  describe 'workflows_clone_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflows_create
  # @param workflow 
  # @param [Hash] opts the optional parameters
  # @return [Workflow]
  describe 'workflows_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflows_destroy
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'workflows_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflows_list
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description 
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [String] :name 
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [String] :run_environment__uuid 
  # @option opts [String] :search A search term.
  # @return [PaginatedWorkflowSummaryList]
  describe 'workflows_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflows_partial_update
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedWorkflow] :patched_workflow 
  # @return [Workflow]
  describe 'workflows_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflows_retrieve
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [Workflow]
  describe 'workflows_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflows_update
  # @param uuid 
  # @param workflow 
  # @param [Hash] opts the optional parameters
  # @return [Workflow]
  describe 'workflows_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
