=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudReactorAPIClient::AwsEcsServiceLoadBalancerDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudReactorAPIClient::AwsEcsServiceLoadBalancerDetails do
  let(:instance) { CloudReactorAPIClient::AwsEcsServiceLoadBalancerDetails.new }

  describe 'test an instance of AwsEcsServiceLoadBalancerDetails' do
    it 'should create an instance of AwsEcsServiceLoadBalancerDetails' do
      expect(instance).to be_instance_of(CloudReactorAPIClient::AwsEcsServiceLoadBalancerDetails)
    end
  end
  describe 'test attribute "target_group_arn"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "container_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "container_port"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
