=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudReactorAPIClient::AwsEcsLaunchType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudReactorAPIClient::AwsEcsLaunchType do
  let(:instance) { CloudReactorAPIClient::AwsEcsLaunchType.new }

  describe 'test an instance of AwsEcsLaunchType' do
    it 'should create an instance of AwsEcsLaunchType' do
      expect(instance).to be_instance_of(CloudReactorAPIClient::AwsEcsLaunchType)
    end
  end
end
