=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudReactorAPIClient::Group
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudReactorAPIClient::Group do
  let(:instance) { CloudReactorAPIClient::Group.new }

  describe 'test an instance of Group' do
    it 'should create an instance of Group' do
      expect(instance).to be_instance_of(CloudReactorAPIClient::Group)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
