=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudReactorAPIClient::TaskExecutionStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudReactorAPIClient::TaskExecutionStatus do
  let(:instance) { CloudReactorAPIClient::TaskExecutionStatus.new }

  describe 'test an instance of TaskExecutionStatus' do
    it 'should create an instance of TaskExecutionStatus' do
      expect(instance).to be_instance_of(CloudReactorAPIClient::TaskExecutionStatus)
    end
  end
end
