=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudReactorAPIClient::TimeoutBehaviorEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudReactorAPIClient::TimeoutBehaviorEnum do
  let(:instance) { CloudReactorAPIClient::TimeoutBehaviorEnum.new }

  describe 'test an instance of TimeoutBehaviorEnum' do
    it 'should create an instance of TimeoutBehaviorEnum' do
      expect(instance).to be_instance_of(CloudReactorAPIClient::TimeoutBehaviorEnum)
    end
  end
end
