=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudReactorAPIClient::UnknownExecutionMethodCapability
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudReactorAPIClient::UnknownExecutionMethodCapability do
  let(:instance) { CloudReactorAPIClient::UnknownExecutionMethodCapability.new }

  describe 'test an instance of UnknownExecutionMethodCapability' do
    it 'should create an instance of UnknownExecutionMethodCapability' do
      expect(instance).to be_instance_of(CloudReactorAPIClient::UnknownExecutionMethodCapability)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "capabilities"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
