=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.3.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudReactorAPIClient::WorkflowExecutionRunReason
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudReactorAPIClient::WorkflowExecutionRunReason do
  let(:instance) { CloudReactorAPIClient::WorkflowExecutionRunReason.new }

  describe 'test an instance of WorkflowExecutionRunReason' do
    it 'should create an instance of WorkflowExecutionRunReason' do
      expect(instance).to be_instance_of(CloudReactorAPIClient::WorkflowExecutionRunReason)
    end
  end
end
