=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.3.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudReactorAPIClient::WorkflowExecutionStopReason
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CloudReactorAPIClient::WorkflowExecutionStopReason do
  let(:instance) { CloudReactorAPIClient::WorkflowExecutionStopReason.new }

  describe 'test an instance of WorkflowExecutionStopReason' do
    it 'should create an instance of WorkflowExecutionStopReason' do
      expect(instance).to be_instance_of(CloudReactorAPIClient::WorkflowExecutionStopReason)
    end
  end
end
