=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.3.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CloudReactorAPIClient
  # A ModelSerializer that takes additional arguments for \"fields\", \"omit\" and \"expand\" in order to control which fields are displayed, and whether to replace simple values with complex, nested serializations
  class AwsEcsRunEnvironmentExecutionMethodCapability
    attr_accessor :type

    attr_accessor :capabilities

    attr_accessor :tags

    attr_accessor :default_subnets

    attr_accessor :default_subnet_infrastructure_website_urls

    attr_accessor :default_launch_type

    attr_accessor :supported_launch_types

    attr_accessor :default_cluster_arn

    attr_accessor :default_cluster_infrastructure_website_url

    attr_accessor :default_security_groups

    attr_accessor :default_security_group_infrastructure_website_urls

    attr_accessor :default_assign_public_ip

    attr_accessor :default_execution_role

    attr_accessor :default_execution_role_infrastructure_website_url

    attr_accessor :default_task_role

    attr_accessor :default_task_role_infrastructure_website_url

    attr_accessor :default_platform_version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'capabilities' => :'capabilities',
        :'tags' => :'tags',
        :'default_subnets' => :'default_subnets',
        :'default_subnet_infrastructure_website_urls' => :'default_subnet_infrastructure_website_urls',
        :'default_launch_type' => :'default_launch_type',
        :'supported_launch_types' => :'supported_launch_types',
        :'default_cluster_arn' => :'default_cluster_arn',
        :'default_cluster_infrastructure_website_url' => :'default_cluster_infrastructure_website_url',
        :'default_security_groups' => :'default_security_groups',
        :'default_security_group_infrastructure_website_urls' => :'default_security_group_infrastructure_website_urls',
        :'default_assign_public_ip' => :'default_assign_public_ip',
        :'default_execution_role' => :'default_execution_role',
        :'default_execution_role_infrastructure_website_url' => :'default_execution_role_infrastructure_website_url',
        :'default_task_role' => :'default_task_role',
        :'default_task_role_infrastructure_website_url' => :'default_task_role_infrastructure_website_url',
        :'default_platform_version' => :'default_platform_version'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'capabilities' => :'Array<String>',
        :'tags' => :'Hash<String, String>',
        :'default_subnets' => :'Array<String>',
        :'default_subnet_infrastructure_website_urls' => :'Array<String>',
        :'default_launch_type' => :'AwsEcsLaunchType',
        :'supported_launch_types' => :'Array<AwsEcsLaunchType>',
        :'default_cluster_arn' => :'String',
        :'default_cluster_infrastructure_website_url' => :'String',
        :'default_security_groups' => :'Array<String>',
        :'default_security_group_infrastructure_website_urls' => :'Array<String>',
        :'default_assign_public_ip' => :'Boolean',
        :'default_execution_role' => :'String',
        :'default_execution_role_infrastructure_website_url' => :'String',
        :'default_task_role' => :'String',
        :'default_task_role_infrastructure_website_url' => :'String',
        :'default_platform_version' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tags',
        :'default_subnets',
        :'default_launch_type',
        :'supported_launch_types',
        :'default_security_groups',
        :'default_assign_public_ip',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CloudReactorAPIClient::AwsEcsRunEnvironmentExecutionMethodCapability` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CloudReactorAPIClient::AwsEcsRunEnvironmentExecutionMethodCapability`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'capabilities')
        if (value = attributes[:'capabilities']).is_a?(Array)
          self.capabilities = value
        end
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Hash)
          self.tags = value
        end
      end

      if attributes.key?(:'default_subnets')
        if (value = attributes[:'default_subnets']).is_a?(Array)
          self.default_subnets = value
        end
      end

      if attributes.key?(:'default_subnet_infrastructure_website_urls')
        if (value = attributes[:'default_subnet_infrastructure_website_urls']).is_a?(Array)
          self.default_subnet_infrastructure_website_urls = value
        end
      end

      if attributes.key?(:'default_launch_type')
        self.default_launch_type = attributes[:'default_launch_type']
      end

      if attributes.key?(:'supported_launch_types')
        if (value = attributes[:'supported_launch_types']).is_a?(Array)
          self.supported_launch_types = value
        end
      end

      if attributes.key?(:'default_cluster_arn')
        self.default_cluster_arn = attributes[:'default_cluster_arn']
      end

      if attributes.key?(:'default_cluster_infrastructure_website_url')
        self.default_cluster_infrastructure_website_url = attributes[:'default_cluster_infrastructure_website_url']
      end

      if attributes.key?(:'default_security_groups')
        if (value = attributes[:'default_security_groups']).is_a?(Array)
          self.default_security_groups = value
        end
      end

      if attributes.key?(:'default_security_group_infrastructure_website_urls')
        if (value = attributes[:'default_security_group_infrastructure_website_urls']).is_a?(Array)
          self.default_security_group_infrastructure_website_urls = value
        end
      end

      if attributes.key?(:'default_assign_public_ip')
        self.default_assign_public_ip = attributes[:'default_assign_public_ip']
      end

      if attributes.key?(:'default_execution_role')
        self.default_execution_role = attributes[:'default_execution_role']
      end

      if attributes.key?(:'default_execution_role_infrastructure_website_url')
        self.default_execution_role_infrastructure_website_url = attributes[:'default_execution_role_infrastructure_website_url']
      end

      if attributes.key?(:'default_task_role')
        self.default_task_role = attributes[:'default_task_role']
      end

      if attributes.key?(:'default_task_role_infrastructure_website_url')
        self.default_task_role_infrastructure_website_url = attributes[:'default_task_role_infrastructure_website_url']
      end

      if attributes.key?(:'default_platform_version')
        self.default_platform_version = attributes[:'default_platform_version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@default_cluster_arn.nil? && @default_cluster_arn.to_s.length > 1000
        invalid_properties.push('invalid value for "default_cluster_arn", the character length must be smaller than or equal to 1000.')
      end

      if !@default_execution_role.nil? && @default_execution_role.to_s.length > 1000
        invalid_properties.push('invalid value for "default_execution_role", the character length must be smaller than or equal to 1000.')
      end

      if !@default_task_role.nil? && @default_task_role.to_s.length > 1000
        invalid_properties.push('invalid value for "default_task_role", the character length must be smaller than or equal to 1000.')
      end

      if !@default_platform_version.nil? && @default_platform_version.to_s.length > 10
        invalid_properties.push('invalid value for "default_platform_version", the character length must be smaller than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@default_cluster_arn.nil? && @default_cluster_arn.to_s.length > 1000
      return false if !@default_execution_role.nil? && @default_execution_role.to_s.length > 1000
      return false if !@default_task_role.nil? && @default_task_role.to_s.length > 1000
      return false if !@default_platform_version.nil? && @default_platform_version.to_s.length > 10
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] default_cluster_arn Value to be assigned
    def default_cluster_arn=(default_cluster_arn)
      if !default_cluster_arn.nil? && default_cluster_arn.to_s.length > 1000
        fail ArgumentError, 'invalid value for "default_cluster_arn", the character length must be smaller than or equal to 1000.'
      end

      @default_cluster_arn = default_cluster_arn
    end

    # Custom attribute writer method with validation
    # @param [Object] default_execution_role Value to be assigned
    def default_execution_role=(default_execution_role)
      if !default_execution_role.nil? && default_execution_role.to_s.length > 1000
        fail ArgumentError, 'invalid value for "default_execution_role", the character length must be smaller than or equal to 1000.'
      end

      @default_execution_role = default_execution_role
    end

    # Custom attribute writer method with validation
    # @param [Object] default_task_role Value to be assigned
    def default_task_role=(default_task_role)
      if !default_task_role.nil? && default_task_role.to_s.length > 1000
        fail ArgumentError, 'invalid value for "default_task_role", the character length must be smaller than or equal to 1000.'
      end

      @default_task_role = default_task_role
    end

    # Custom attribute writer method with validation
    # @param [Object] default_platform_version Value to be assigned
    def default_platform_version=(default_platform_version)
      if !default_platform_version.nil? && default_platform_version.to_s.length > 10
        fail ArgumentError, 'invalid value for "default_platform_version", the character length must be smaller than or equal to 10.'
      end

      @default_platform_version = default_platform_version
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          capabilities == o.capabilities &&
          tags == o.tags &&
          default_subnets == o.default_subnets &&
          default_subnet_infrastructure_website_urls == o.default_subnet_infrastructure_website_urls &&
          default_launch_type == o.default_launch_type &&
          supported_launch_types == o.supported_launch_types &&
          default_cluster_arn == o.default_cluster_arn &&
          default_cluster_infrastructure_website_url == o.default_cluster_infrastructure_website_url &&
          default_security_groups == o.default_security_groups &&
          default_security_group_infrastructure_website_urls == o.default_security_group_infrastructure_website_urls &&
          default_assign_public_ip == o.default_assign_public_ip &&
          default_execution_role == o.default_execution_role &&
          default_execution_role_infrastructure_website_url == o.default_execution_role_infrastructure_website_url &&
          default_task_role == o.default_task_role &&
          default_task_role_infrastructure_website_url == o.default_task_role_infrastructure_website_url &&
          default_platform_version == o.default_platform_version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, capabilities, tags, default_subnets, default_subnet_infrastructure_website_urls, default_launch_type, supported_launch_types, default_cluster_arn, default_cluster_infrastructure_website_url, default_security_groups, default_security_group_infrastructure_website_urls, default_assign_public_ip, default_execution_role, default_execution_role_infrastructure_website_url, default_task_role, default_task_role_infrastructure_website_url, default_platform_version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CloudReactorAPIClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
