=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CloudReactorAPIClient
  class RuleTypeEnum
    ALWAYS = "always".freeze
    SUCCESS = "success".freeze
    FAILURE = "failure".freeze
    TIMEOUT = "timeout".freeze
    EXIT_CODE = "exit_code".freeze
    THRESHOLD = "threshold".freeze
    CUSTOM = "custom".freeze
    DEFAULT = "default".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = RuleTypeEnum.constants.select { |c| RuleTypeEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #RuleTypeEnum" if constantValues.empty?
      value
    end
  end
end
