=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'date'
require 'time'

module CloudReactorAPIClient
  class ThresholdPropertyEnum
    EXECUTION_TIME = "execution_time".freeze
    SUCCESS_RATIO = "success_ratio".freeze
    FAILURE_RATIO = "failure_ratio".freeze
    SKIPPED_RATIO = "skipped_ratio".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ThresholdPropertyEnum.constants.select { |c| ThresholdPropertyEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ThresholdPropertyEnum" if constantValues.empty?
      value
    end
  end
end
