=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.2.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CloudReactorAPIClient
  class TimeoutBehaviorEnum
    ALWAYS_FAIL_WORKFLOW = "always_fail_workflow".freeze
    ALWAYS_TIMEOUT_WORKFLOW = "always_timeout_workflow".freeze
    FAIL_WORKFLOW_IF_UNHANDLED = "fail_workflow_if_unhandled".freeze
    TIMEOUT_WORKFLOW_IF_UNHANDLED = "timeout_workflow_if_unhandled".freeze
    IGNORE = "ignore".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TimeoutBehaviorEnum.constants.select { |c| TimeoutBehaviorEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TimeoutBehaviorEnum" if constantValues.empty?
      value
    end
  end
end
