=begin
#CloudReactor API

#CloudReactor API Documentation

The version of the OpenAPI document: 0.3.0
Contact: jeff@cloudreactor.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CloudReactorAPIClient
  class WorkflowExecutionRunReason
    EXPLICIT_START = "EXPLICIT_START".freeze
    SCHEDULED_START = "SCHEDULED_START".freeze
    EXPLICIT_RETRY = "EXPLICIT_RETRY".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = WorkflowExecutionRunReason.constants.select { |c| WorkflowExecutionRunReason::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #WorkflowExecutionRunReason" if constantValues.empty?
      value
    end
  end
end
